### ISSUE TITLE
I *think* it worked... what is '{print $3}' for?

### ISSUE THREAD

**Issue by bliedblad** [goeland86/extractSDImage#1]
In my case, had to modify the script three places:
1) Set 'DISK=/dev/sdb' to get to my USB card reader...
2) Set 'PART="$DISK""1", again to get to the correct partition
3) modify the "COUNT" line to use '/dev/sdb' just after 'sudo parted'

Command to execute was then:
. extractSDImage.sh MyImageName.img.xz

About to test the archive via extract -> flash, but...
**I'm wondering what the $3 is for on the "COUNT" line.** 

I thought that $3 is a reference to the third command-line parameter, which I didn't have, so I'm concerned my result may not be what I'm expecting.

Thanks Jon

**Comment by goeland86** [comment]
In this case the print $3 and print $1 are awk syntax. Notice how they're within an awk command with ' surrounding it? They're not bash arguments, they're columns from the awk array currently evaluated.
