### ISSUE TITLE
Transfer hangs after ~200MB on ArchLinux

### ISSUE THREAD

**Issue by bliedblad** [goeland86/extractSDImage#3]
Hi Jon, 

I'm currently running a Macbook Pro, so to use this script I have to run Linux in a virtual machine (VirtualBox) and pass in the uSD card in via a USB adapter.

I have an OLD Debian Distro (3.16) which seems to run the script just fine, but my newer Linux platform (Arch) hangs (the progress bar stops all motion and MiB/s goes to zero). 

To get control back on the terminal I have to eject the USB (virtual machine eject). 

Are you aware of any reason the script would hang on ArchLinux?

I am considering Arch Linux for my next PC mainly because of the AUR, but will have to opt for some Debian/Ubuntu variant if I can't get Arch to work with simple scripts like this.

**Comment by goeland86** [comment]
hi,

From what I suspect, you're having a USB IO issue with the Arch kernel maybe? It would be interesting to look at the output of dmesg after that crash happened before "unplugging" the USB. I doubt it has anything to do with Arch VS Debian/Ubuntu really, the script uses very standard commands in the way they're meant to be used on any Linux platform. (Or at least I hope that's the case).

I run Gentoo at home and the script works fine on that machine as well...

Maybe see if you can get support from the Arch guys when you isolate what kernel issue you're having?

**Comment by bliedblad** [comment]
I hope that's the case too... It's just odd that it will work with Debian.

When it gets into this state, I still see the uSD-USB adapter's LED flashing, so it's as if it is still working, but the output file's size stops increasing and progress bar stops moving...

Thanks for the response, I'll try other avenues.

**Comment by goeland86** [comment]
One last comment about that - since you're running in a virtual machine, maybe make sure you have enough free disk space in the Arch image you're running? That could also be a factor if your VM's FS is full. Good hunting!
